### ISSUE TITLE
Neovim remote 

### ISSUE THREAD

**Issue by krillin666** [vipzhicheng/logseq-plugin-vim-editor#2]
Hi @vipzhicheng , thank you so much for bringing more VIM functionality to Logseq. Its a Godsend !

How hard do you think it would be that instead of opening up the current editor, we leverage the NeoVim's remote functionality to open up it in a nvim window. This way we could take advantage of the personal configs one has in his nvim.
Some examples of top of my head would be:

- Auto-completion (cmp, coq-vim, etc)
- Automatic error with Ctrl+L (inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u)
- Snippets + completion for markdown
- much more !

**Comment by vipzhicheng** [comment]
I digged into it in hours and the short answer would be NO!

There is a possible plugin in market called open with, it uses system url scheme to trigger opening in external app. but on Mac, iTerm and Terminal are all not registered any schemes.

I tried MacVIM, yes, it registered `mvim://` to let chrome open it in browser, but it is a VIM GUI not NeoVIM GUI, I tried a lot of NeoVIM GUIs, none of them works that way.

And I noticed VSCode registered URL scheme: `vscode://`, so I install a VSCODE NeoVIM plugin, and make all markdown opened with VSCode, Then I partly implemented the workflow.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/1209538/159631255-2861c4ca-d86e-42e3-a072-384e31ce2ddc.png">

<img width="669" alt="image" src="https://user-images.githubusercontent.com/1209538/159631484-51244217-e978-40c0-932c-7c9319d48704.png">

The solution is not a perfect solution, but just the best answer I can give for now.

**Comment by vipzhicheng** [comment]
In the latest release, I provide a way, `:copy-path`, to give the page or journal absolute path, so you can copy and paste to terminal to edit it in Vim.

**Comment by fakeyanss** [comment]
This can help you.

https://forum.obsidian.md/t/open-note-in-obsidian-from-within-vim-and-vice-versa/6837/5

<img width="1000" alt="image" src="https://github.com/vipzhicheng/logseq-plugin-vim-editor/assets/30440198/c3bcaffb-3976-4d29-a285-81b8e032ce2c">

<img width="1440" alt="image" src="https://github.com/vipzhicheng/logseq-plugin-vim-editor/assets/30440198/3c981cbd-05de-4a0e-a75f-dbe6e187619b">

**Comment by fakeyanss** [comment]
Well, I found Alacritty is more convenient.

Using `Run Shell Script` in Automator, and set as:
```bash
nohup /Applications/Alacritty.app/Contents/MacOS/alacritty -e vim "$1" > /dev/null 2>&1 &
```

I can open a page by default app(set to TerminalVim.app before) and edit. And just type `:wq` in normal mode, the alacritty window will be closed too.

<img width="1000" alt="image" src="https://github.com/vipzhicheng/logseq-plugin-vim-editor/assets/30440198/17926c1d-9892-4a0c-a599-a8ab75117f9b">
